projects:
  app:
    schemaPath: src/schema.graphql
    includes: ['**/*.graphql']
    extensions:
      endpoints:
        default: https://the-source-backend.herokuapp.com/graphql
  prisma:
    schemaPath: 'src/generated/prisma.graphql'
    extensions:
      prisma: database/prisma.yml
